# Generated by Django 4.0.6 on 2022-09-02 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='dhttps://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png', upload_to='portfolio/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='dhttps://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__340.png', upload_to='portfolio/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
