# Generated by Django 4.0.6 on 2022-09-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_image', models.ImageField(upload_to='AboutImages/')),
                ('video', models.FileField(upload_to='AboutVideos/')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Fast Cars',
            },
        ),
    ]
