# Generated by Django 4.0.6 on 2022-09-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_about_author_about_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(),
        ),
    ]
