# Generated by Django 4.0.6 on 2022-09-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactdetail_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='detail_icon',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='details',
        ),
    ]
