# Generated by Django 4.0.6 on 2022-09-15 20:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_contactinfo_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, verbose_name='car_title')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('car_photo', models.ImageField(upload_to='cars_images', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])])),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brand')),
            ],
        ),
    ]
