# Generated by Django 4.0.6 on 2022-09-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_brand_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
